#!/bin/bash
# 
# Copyright 2010 Google Inc. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS-IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Install postflight script
#
# Note: this script ends up running from the directory that the installer
# was invoked from, e.g.  maybe / from the GUI, or a /Volumes/blah if
# invoked from CLI

set -e

export PATH="$PATH:/usr/bin"
PKG="$1"
DEFAULT_PATH="$2"
TARGET_PATH="$3"
RESOURCES="${PKG}/Contents/Resources"
BASETMPDIR="${TARGET_PATH}/tmp/"
OSX=$(sw_vers -productVersion | cut -d. -f1-2)
VERSION="1.0.1"

### set up sane logging
d=$(date '+%Y%m%d%H%M')
exec 2>&1
exec 1> "${BASETMPDIR}/postflight.${d}.$$.log"

### create temp work directory
TMPDIR=$(mktemp -d ${BASETMPDIR}/postflightXXXXXX)
ORIGPWD="${PWD}"
#trap "rm -rf ${TMPDIR}" EXIT


### install supplied eggs, like M2Crypto.

if [ "${OSX}" = "10.6" ] && [ -x "/usr/bin/easy_install-2.6" ]; then
  EZ="/usr/bin/easy_install-2.6"
else
  EZ="/usr/bin/easy_install"
fi

[ -x "$EZ" ]

for egg in ${RESOURCES}/*-${OSX}-*.egg ; do
  ${EZ} -N "${egg}"
done

### install dependencies
# setuptools does not like to upgrade some packages automatically
# when running setup.py below, e.g. python-dateutil from 1.2 to 1.4.
# so, just upgrade them all in advance. :(
${EZ} -U setuptools
${EZ} -U python-dateutil
${EZ} -U pyasn1
${EZ} -U tlslite
${EZ} -U pyyaml
${EZ} -U google_apputils

### install main source package

tar -zxf "${RESOURCES}/simian-${VERSION}.tar.gz" -C "${TMPDIR}"
cd "${TMPDIR}/simian-${VERSION}"
mkdir -p src/tests  # fake out google test
python setup.py install 2>&1
cd "${ORIGPWD}"

### update munki configuration

server=`python -c "from simian import settings ; print '%s.%s' % (settings.SUBDOMAIN, settings.DOMAIN)"`
defaults write /Library/Preferences/ManagedInstalls SoftwareRepoURL https://${server}

### small file operations

chmod 750 /etc/simian/ssl/private_keys

for f in /etc/simian/simian.cfg; do
  if [ ! -f "${f}" -a -f "${f}+" ]; then
    mv "${f}+" "${f}"
  else
    rm "${f}+"
  fi
done

### TODO: remove any files unnecessary on clients
